name: Node automate test runnner
on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    node-test:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: install node
              uses: actions/setup-node@v3
              with:
                node-version: '22.22.0'

            - name: Install dependencies
              run: npm install

            - name: Run tests
              run: npm test

              

            

            

            