name: Node automate test runnner
on:[push , pull_request]
jobs:
    node-test:
        runs-on : ubuntu-latest
        steps:
            - name: Checkout code
            - uses: actions/checkout

            - name: install node
            - uses: actions/setup-node@v3
              with:
                node-version: '22.22.0'

            